apiVersion: v1
kind: Secret
metadata:
  name: pca-secret
  namespace: default
data:
  AWS_ACCESS_KEY_ID: {{BASE64_ACCESSKEY}}
  AWS_SECRET_ACCESS_KEY: {{BASE64_SECRETKEY}}
  # AWS_SESSION_TOKEN is optional and only needed for temporary credentials
  # AWS_SESSION_TOKEN: {{BASE64_SESSIONTOKEN}}